server:
  port: 8022
spring:
  #给项目来个名字
  application:
    name: rabbitmq-consumer
  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.137.123
    port: 5672
    username: admin
    password: admin
    #虚拟host 可以不设置,使用server默认host
    #virtual-host: JCcccHost
